## 1. Classify the algorithms into supervised and unsupervised machine learning algorithms
[ Support vector machine, Decision tree, Hierarchical clustering, K-nearest neighbor, K-mean clustering, Naïve Bayes, Principal component analysis, Linear discriminant analysis, independent component analysis]

## Supervised Machine Learning

###  1 - Support vetor machine
###  2 - Decision Tree
###  3 - K-nearest neighbour
###  4 - Naive Bayes
###  5 - Linear discriminanat analysis

## Unsupervised Machine Learning

### 1 - Hierarchical clustering
### 2 - K-mean clustering
### 3 - Principal component analysis
### 4 - independent component analysis

## '''2. Given a data set, we are going to see how feature extraction can be done. Electric motor drive data set is given. (electric_motor.csv).

### Steps for feature extraction'''

In [1]:
import pandas as pd
import numpy as np

## (a) Load the data into the variable explorer

In [2]:
df=pd.read_csv(r'C:\Users\mukesh\Machine Learning\motor_electric.csv' )

In [3]:
df

ambient   coolant       u_d       u_q  motor_speed    torque  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428 -0.250182   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429 -0.249133   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428 -0.249431   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430 -0.248636   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429 -0.248701   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428 -0.255640   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437 -0.255640   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430 -0.255640   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432 -0.255640   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431 -0.255640   

             i_d       i_q        pm  stator_yoke  stator_tooth  \
0       1.029572 -0.245860 -2.522071    -1.831422     -2.066143   
1       1.029509 -0.245832 -2.522418    -1.830969     -2.064859   
2       1.029448 -0.245818 -2.522673    -1.830400     -2.064073   
3       1.032845 -0.246955 -2.521639    -1.830333     -2.063137   
4       1.031807 -0.246610 -2.521900    -1.830498     -2.062795   
...          ...       ...       ...          ...           ...   
998065  1.029142 -0.245723  0.429853     1.018568      0.836084   
998066  1.029148 -0.245736  0.429751     1.013416      0.834438   
998067  1.029191 -0.245701  0.429439     1.002906      0.833936   
998068  1.029147 -0.245727  0.429558     0.999157      0.830504   
998069  1.029141 -0.245722  0.429166     0.987163      0.828046   

        stator_winding  profile_id  
0            -2.018033           4  
1            -2.017631           4  
2            -2.017343           4  
3            -2.017632           4  
4            -2.018145           4  
...                ...         ...  
998065        0.494725          72  
998066        0.494279          72  
998067        0.492666          72  
998068        0.490581          72  
998069        0.489382          72  

[998070 rows x 13 columns]

In [4]:
#checking null values
df.isnull().sum()

ambient           0
coolant           0
u_d               0
u_q               0
motor_speed       0
torque            0
i_d               0
i_q               0
pm                0
stator_yoke       0
stator_tooth      0
stator_winding    0
profile_id        0
dtype: int64

In [5]:
pd.unique(df['profile_id'])

array([ 4,  6, 10, 11, 20, 27, 29, 30, 31, 32, 36, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       72], dtype=int64)

In [6]:
df.describe()

ambient        coolant            u_d            u_q  \
count  998070.000000  998070.000000  998070.000000  998070.000000   
mean       -0.003905       0.004723       0.004780      -0.005690   
std         0.993127       1.002423       0.997878       1.002330   
min        -8.573954      -1.429349      -1.655373      -1.861463   
25%        -0.599385      -1.037925      -0.826359      -0.927390   
50%         0.266157      -0.177187       0.267542      -0.099818   
75%         0.686675       0.650709       0.358491       0.852625   
max         2.967117       2.649032       2.274734       1.793498   

         motor_speed         torque            i_d            i_q  \
count  998070.000000  998070.000000  998070.000000  998070.000000   
mean       -0.006336      -0.003333       0.006043      -0.003194   
std         1.001229       0.997907       0.998994       0.997912   
min        -1.371529      -3.345953      -3.245874      -3.341639   
25%        -0.951892      -0.266917      -0.756296      -0.257269   
50%        -0.140246      -0.187246       0.213935      -0.190076   
75%         0.853584       0.547171       1.013975       0.499260   
max         2.024164       3.016971       1.060937       2.914185   

                  pm    stator_yoke   stator_tooth  stator_winding  \
count  998070.000000  998070.000000  998070.000000   998070.000000   
mean       -0.004396       0.000609      -0.002208       -0.003935   
std         0.995686       1.001049       0.999597        0.998343   
min        -2.631991      -1.834688      -2.066143       -2.019973   
25%        -0.672308      -0.747265      -0.761951       -0.725622   
50%         0.094367      -0.057226       0.005085        0.006536   
75%         0.680691       0.697344       0.772239        0.725660   
max         2.917456       2.449158       2.326668        2.653781   

          profile_id  
count  998070.000000  
mean       50.732001  
std        22.073125  
min         4.000000  
25%        32.000000  
50%        56.000000  
75%        68.000000  
max        81.000000

In [7]:
# checking duplicate values
df.duplicated().sum()

0

In [8]:
df.shape

(998070, 13)

In [9]:
#checking outliers
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

outliers=df[(df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR)) ]
outliers.isna().sum()


ambient           959578
coolant           998070
u_d               980020
u_q               998070
motor_speed       998070
torque            870767
i_d               998070
i_q               849535
pm                996569
stator_yoke       998070
stator_tooth      998070
stator_winding    998070
profile_id        998070
dtype: int64

In [10]:
#removing outliers
df1=df[~((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
df1.shape

(814996, 13)

In [11]:
df1.describe()

ambient        coolant            u_d            u_q  \
count  814996.000000  814996.000000  814996.000000  814996.000000   
mean        0.074327       0.043378      -0.108752       0.073228   
std         0.842397       1.020929       0.880459       1.062721   
min        -2.528432      -1.326642      -1.654878      -1.692953   
25%        -0.549461      -1.034215      -0.872168      -1.167716   
50%         0.269779      -0.131247       0.240986       0.082905   
75%         0.686956       0.838960       0.342796       0.960540   
max         2.615644       2.297432       2.135743       1.793498   

         motor_speed         torque            i_d            i_q  \
count  814996.000000  814996.000000  814996.000000  814996.000000   
mean        0.057953       0.055707       0.112811       0.057467   
std         1.056624       0.637751       0.994801       0.635833   
min        -1.371529      -1.488004      -3.109984      -1.392057   
25%        -1.141301      -0.255640      -0.643348      -0.245732   
50%        -0.004975      -0.185800       0.453488      -0.176573   
75%         0.997569       0.464114       1.029133       0.481189   
max         2.024164       1.768235       1.060255       1.633992   

                  pm    stator_yoke   stator_tooth  stator_winding  \
count  814996.000000  814996.000000  814996.000000   814996.000000   
mean        0.045887      -0.005105      -0.038661       -0.082340   
std         0.956329       1.004616       0.990678        0.967570   
min        -2.628648      -1.834688      -2.066143       -2.019973   
25%        -0.602911      -0.770572      -0.778084       -0.791304   
50%         0.111043      -0.057719      -0.033528       -0.078244   
75%         0.701153       0.674934       0.769904        0.626848   
max         2.710098       2.449158       2.326668        2.573466   

          profile_id  
count  814996.000000  
mean       50.858718  
std        22.774148  
min         4.000000  
25%        31.000000  
50%        57.000000  
75%        69.000000  
max        81.000000

In [12]:
df.corr()

ambient   coolant       u_d       u_q  motor_speed    torque  \
ambient         1.000000  0.434435  0.194754  0.087430     0.078283 -0.262264   
coolant         0.434435  1.000000  0.178708  0.027851    -0.033332 -0.189617   
u_d             0.194754  0.178708  1.000000 -0.027472    -0.233828 -0.821325   
u_q             0.087430  0.027851 -0.027472  1.000000     0.716897 -0.037262   
motor_speed     0.078283 -0.033332 -0.233828  0.716897     1.000000  0.024517   
torque         -0.262264 -0.189617 -0.821325 -0.037262     0.024517  1.000000   
i_d             0.005605  0.108489  0.358517 -0.181855    -0.722914 -0.239059   
i_q            -0.260562 -0.186060 -0.796586 -0.026348     0.006323  0.996560   
pm              0.501496  0.430548 -0.082564  0.101236     0.332419 -0.072905   
stator_yoke     0.451616  0.874037  0.041428  0.106186     0.182564 -0.092207   
stator_tooth    0.396742  0.689003 -0.066256  0.149017     0.333909 -0.011055   
stator_winding  0.301883  0.509298 -0.150714  0.125445     0.393154  0.080981   
profile_id      0.384565  0.499669  0.300771 -0.122260    -0.166225 -0.257446   

                     i_d       i_q        pm  stator_yoke  stator_tooth  \
ambient         0.005605 -0.260562  0.501496     0.451616      0.396742   
coolant         0.108489 -0.186060  0.430548     0.874037      0.689003   
u_d             0.358517 -0.796586 -0.082564     0.041428     -0.066256   
u_q            -0.181855 -0.026348  0.101236     0.106186      0.149017   
motor_speed    -0.722914  0.006323  0.332419     0.182564      0.333909   
torque         -0.239059  0.996560 -0.072905    -0.092207     -0.011055   
i_d             1.000000 -0.204230 -0.299227    -0.179903     -0.387712   
i_q            -0.204230  1.000000 -0.086486    -0.098753     -0.025191   
pm             -0.299227 -0.086486  1.000000     0.695014      0.768352   
stator_yoke    -0.179903 -0.098753  0.695014     1.000000      0.949898   
stator_tooth   -0.387712 -0.025191  0.768352     0.949898      1.000000   
stator_winding -0.539924  0.060949  0.729561     0.845144      0.965633   
profile_id      0.142368 -0.256127  0.156735     0.398021      0.280994   

                stator_winding  profile_id  
ambient               0.301883    0.384565  
coolant               0.509298    0.499669  
u_d                  -0.150714    0.300771  
u_q                   0.125445   -0.122260  
motor_speed           0.393154   -0.166225  
torque                0.080981   -0.257446  
i_d                  -0.539924    0.142368  
i_q                   0.060949   -0.256127  
pm                    0.729561    0.156735  
stator_yoke           0.845144    0.398021  
stator_tooth          0.965633    0.280994  
stator_winding        1.000000    0.181908  
profile_id            0.181908    1.000000

## spliting the data into x and y

In [36]:
df1=df.drop(['torque'],axis=1)

In [37]:
df1

ambient   coolant       u_d       u_q  motor_speed       i_d  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428  1.029572   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429  1.029509   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428  1.029448   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430  1.032845   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429  1.031807   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428  1.029142   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437  1.029148   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430  1.029191   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432  1.029147   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431  1.029141   

             i_q        pm  stator_yoke  stator_tooth  stator_winding  \
0      -0.245860 -2.522071    -1.831422     -2.066143       -2.018033   
1      -0.245832 -2.522418    -1.830969     -2.064859       -2.017631   
2      -0.245818 -2.522673    -1.830400     -2.064073       -2.017343   
3      -0.246955 -2.521639    -1.830333     -2.063137       -2.017632   
4      -0.246610 -2.521900    -1.830498     -2.062795       -2.018145   
...          ...       ...          ...           ...             ...   
998065 -0.245723  0.429853     1.018568      0.836084        0.494725   
998066 -0.245736  0.429751     1.013416      0.834438        0.494279   
998067 -0.245701  0.429439     1.002906      0.833936        0.492666   
998068 -0.245727  0.429558     0.999157      0.830504        0.490581   
998069 -0.245722  0.429166     0.987163      0.828046        0.489382   

        profile_id  
0                4  
1                4  
2                4  
3                4  
4                4  
...            ...  
998065          72  
998066          72  
998067          72  
998068          72  
998069          72  

[998070 rows x 12 columns]

In [56]:
x=df1.iloc[:,0:13].values

In [57]:
x

array([[-7.5214297e-01, -1.1184461e+00,  3.2793520e-01, ...,
        -2.0661428e+00, -2.0180326e+00,  4.0000000e+00],
       [-7.7126324e-01, -1.1170206e+00,  3.2966480e-01, ...,
        -2.0648587e+00, -2.0176313e+00,  4.0000000e+00],
       [-7.8289163e-01, -1.1166813e+00,  3.3277150e-01, ...,
        -2.0640730e+00, -2.0173435e+00,  4.0000000e+00],
       ...,
       [-4.2350100e-02,  3.0741498e-01,  3.3094567e-01, ...,
         8.3393570e-01,  4.9266600e-01,  7.2000000e+01],
       [-3.9433220e-02,  3.0208160e-01,  3.3098695e-01, ...,
         8.3050430e-01,  4.9058100e-01,  7.2000000e+01],
       [-4.3802520e-02,  3.1266590e-01,  3.3082953e-01, ...,
         8.2804570e-01,  4.8938242e-01,  7.2000000e+01]])

In [58]:
y=df['torque'].values
y

array([-0.2501821 , -0.2491333 , -0.24943107, ..., -0.25563973,
       -0.25563973, -0.25563973])

## split the data in train and test

In [59]:
from sklearn.model_selection import train_test_split

In [74]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=5)

In [75]:
x_train.shape

(748552, 12)

In [76]:
x_test.shape

(249518, 12)

## Scaling of X

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
sc=StandardScaler()

In [79]:
x_train=sc.fit_transform(x_train)

In [80]:
x_train=sc.transform(x_train)

In [81]:
x_test=sc.transform(x_test)

## (b) Construct covariance matrix

In [88]:
# Determine covariance matrix
cov_matrix = np.cov(x, rowvar=False)
cov_matrix                        

array([[ 9.86300805e-01,  4.32494787e-01,  1.93005042e-01,
         8.70310410e-02,  7.78404221e-02,  5.56047815e-03,
        -2.58230851e-01,  4.95900999e-01,  4.48982998e-01,
         3.93856595e-01,  2.99311687e-01,  8.43019799e+00],
       [ 4.32494787e-01,  1.00485264e+00,  1.78761322e-01,
         2.79838454e-02, -3.34533704e-02,  1.08642049e-01,
        -1.86121348e-01,  4.29729580e-01,  8.77074028e-01,
         6.90395090e-01,  5.09685941e-01,  1.10559849e+01],
       [ 1.93005042e-01,  1.78761322e-01,  9.95760865e-01,
        -2.74776268e-02, -2.33618909e-01,  3.57396729e-01,
        -7.93236133e-01, -8.20336287e-02,  4.13838061e-02,
        -6.60889658e-02, -1.50144593e-01,  6.62486546e+00],
       [ 8.70310410e-02,  2.79838454e-02, -2.74776268e-02,
         1.00466581e+00,  7.19451323e-01, -1.82095355e-01,
        -2.63547055e-02,  1.01033848e-01,  1.06545596e-01,
         1.49304332e-01,  1.25529272e-01, -2.70494308e+00],
       [ 7.78404221e-02, -3.34533704e-02, -2.3361890

## c) Find Eigen values and Eigen vectors of the matrix

In [89]:
# Import eigh method for calculating eigenvalues and eigenvectirs
from numpy.linalg import eigh

In [90]:
# Determine eigenvalues and eigenvectors
egnvalues, egnvectors = eigh(cov_matrix)


In [91]:
egnvalues

array([8.25481143e-04, 8.03924883e-03, 4.06345431e-02, 1.37192014e-01,
       2.43020757e-01, 3.56147063e-01, 7.21703462e-01, 8.35582229e-01,
       1.57203564e+00, 1.87599498e+00, 4.27157403e+00, 4.88137349e+02])

In [92]:
egnvectors

array([[ 7.60458664e-04, -5.05174710e-03,  5.23419617e-02,
        -1.11158470e-01,  1.78986998e-01, -4.00754552e-01,
        -8.19026209e-01,  1.38480295e-01, -6.26234075e-02,
        -2.52417397e-01, -1.85254436e-01,  1.73579108e-02],
       [-1.23808916e-01, -4.06417039e-01, -1.09091810e-01,
         2.91287416e-01, -4.19184951e-01, -4.20424334e-01,
         2.59072966e-01,  3.45613192e-01,  1.94970533e-01,
        -2.85613669e-01, -2.52190850e-01,  2.27669793e-02],
       [-6.04991952e-03,  7.76892919e-03,  1.40743624e-01,
         5.26853008e-01,  4.71070814e-01, -4.50281881e-02,
         1.90877715e-01, -2.11775172e-01, -3.04196155e-01,
        -5.40049526e-01,  1.13699000e-01,  1.36254984e-02],
       [-5.51346630e-03, -1.92725513e-02, -4.25640898e-01,
        -6.39408229e-02,  2.35813520e-01,  1.66108676e-01,
         1.01130215e-01,  5.95845172e-01, -5.71298158e-01,
         1.06801810e-01, -1.67516290e-01, -5.54529954e-03],
       [ 3.63496014e-02, -1.72907861e-02,  6.8284115

## (d) Arrange the Eigen values and Eigen vectors in descending order

In [93]:
# Determine explained variance and select the most important eigenvectors based on explained variance
total_egnvalues = sum(egnvalues)
var_exp = [(i/total_egnvalues) for i in sorted(egnvalues, reverse=True)]
var_exp

[0.9798017915368892,
 0.008574012820620619,
 0.0037655451794879496,
 0.003155430202244744,
 0.001677202054246972,
 0.0014486216754500676,
 0.0007148675081133672,
 0.00048779748846735396,
 0.00027537532552985406,
 8.156269587735235e-05,
 1.6136586177086775e-05,
 1.6569268954758206e-06]

## (e) Select the number of Eigen values such that the ration of selected and total Eigen values is 0.95.

In [101]:
temp=0
for i in var_exp:
    temp+=1
    print(i)
    if temp>0.95:
        print('Number of eigen values are greater than 0.95..:- ',temp)
        break

0.9798017915368892
Number of eigen values are greater than 0.95..:-  1


## (f) After doing this select as many Eigen vector as number of Eigen values selected.

In [99]:
egnpairs = [(np.abs(egnvalues[0]), (egnvectors[:, 1]))]
projectionMatrix = np.hstack((egnpairs[0][1][:, np.newaxis]))

In [100]:
projectionMatrix

array([-5.05174710e-03, -4.06417039e-01,  7.76892919e-03, -1.92725513e-02,
       -1.72907861e-02, -9.06791950e-02,  1.09461670e-02, -5.96751355e-02,
        6.40010575e-01,  2.61553516e-01, -5.86635725e-01,  4.52269586e-05])